### ISSUE TITLE
wish: support require.extensions standard

### ISSUE THREAD

**Issue by markstos** [gagle/node-properties#14]
The `require.extensions` standard allows you to simply a `require` a file in a non-JavaScript format and have it be translated to JavaScript. Popular uses include loading CoffeeScript files, but it's also used for JSON, YAML and a number of other formats. 

[interpret](https://github.com/tkellen/node-interpret) is a module that helps other modules load any file format that has a `require.extensions` loader. 

The `node-config` project has some interest in supporting loading `.properties` files via `interpret`, but for that to happen, this project would need to be updated to support the `requires.extension`.  The good is that's just a few lines of easy code to do. 

Check out how the `JSON` module has implemented it:
https://github.com/aseemk/json5/blob/master/lib/require.js

And how they've documented it:
https://github.com/aseemk/json5#extras

Thanks!

**Comment by gagle** [comment]
require.extensions is deprecated and shouldn't be used.

http://nodejs.org/api/globals.html#globals_require_extensions

**Comment by tkellen** [comment]
- cjsx: https://github.com/SimonDegraeve/node-cjsx/blob/master/index.js
- coco: https://github.com/satyr/coco/blob/master/lib/node.js#L28-L41
- coffeescript: https://github.com/jashkenas/coffeescript/blob/master/lib/coffee-script/register.js
- csv: https://github.com/olalonde/require-csv/blob/master/index.js
- ini: https://github.com/olalonde/require-ini/blob/master/index.js
- json5: https://github.com/aseemk/json5/blob/master/lib/require.js
- 6to5: https://github.com/6to5/6to5/blob/master/lib/6to5/register.js#L120-L123

**Comment by tkellen** [comment]
every one of these modules supports it:
https://github.com/tkellen/node-interpret/blob/master/index.js

**Comment by markstos** [comment]
deprecated Yes, but still useful for cases like this, and as the docs you link to say: "this feature will probably never go away".

**Comment by gagle** [comment]
require-ini and require-csv are both wrappers around modules that do not populat require.extensions. IMO is a bad practice to parse files by using the require() function, even json files. require() loads js modules, it's the equivalence to the ES6 modules.

**Comment by tkellen** [comment]
@gagle Very many popular modules provide opt-in support for this. For example, `require.extensions` is only modified for coffee-script if you require `require('coffee-script/register')`. Would you be willing to add this type of support?

@markstos If @gagle won't add support for this, you can publish a module of your own that does this and I will gladly support it in `interpret`. Unfortunately, you'll have to keep it current with this project.

**Comment by markstos** [comment]
Thanks for the offer @tkellen. I'm more like to consider dropping support for the `properties` format if it hasn't yet reached the level of interest for someone to maintain this common interface.

**Comment by gagle** [comment]
`node-ini` parses ini files but it doesn't register the extension.

`require-ini` registers the extension.

In my TO-DO I have a pending refactoring for this module. I'll create a separate `require-properties` which will register the extension but I don't know when I'll refactor it.

**Comment by gagle** [comment]
v2.0.0 will be released in the next days.

**Comment by tkellen** [comment]
Is this still happening?

**Comment by unrevised6419** [comment]
[require.extensions Stability: 0 - Deprecated](https://nodejs.org/api/modules.html#modules_require_extensions)

**Comment by markstos** [comment]
As the person who opened this issue 4 years ago, I've abandoned supporting `properties` in `node-config` and am closing this issue.
