### ISSUE TITLE
Synchronous Includes

### ISSUE THREAD

**Issue by bgmort** [gagle/node-properties#8]
It's not possible to synchronously get properties with the include property turned on.  There's no informative error, either.  If the include option required the path option to be set, or turned on the path option automatically, that would produce a clean error message instead of the unhandled error when trying to call the undefined callback.

But in my opinion it would be much better to check for the existence of the callback, and use fs.readFileSync if it is undefined.  Then the callback would not have to be required for  the path or include option.  I'd like to help with this, but I won't have the time right away, though I might be able to sometime.

**Comment by gagle** [comment]
What do you mean by "synchronously get properties"? Can you post the code that fails?

This work for me:

---

**CASE 1**

``` javascript
var options = {
    path: true,
    include: true
};
properties.parse ("p1", options, function (error, o){
    if (error) return console.error (error);
    console.log (o); // {a: 1}
});
```

p1

``` text
include p2
```

p2

``` text
a 1
```

---

**CASE 2**

``` javascript
var options = {
    include: true
};
properties.parse ("include p2", options, function (error, o){
    if (error) return console.error (error);
    console.log (o); // {a: 1}
});
```

p2

``` text
a 1
```

**Comment by bgmort** [comment]
I mean get properties synchronously by using the return value of properties.parse instead of passing a callback.

I get can around the issue of not being able to use the path option by reading in the file myself:

``` javascript
var properties = require("properties");
var fs = require("fs");

var options = {
    namespaces: true,
    sections: true,
    variables: true
};

var configFile = __dirname + "/config.properties";
var config = fs.readFileSync(configFile) + ""; //converts buffer to string

module.exports = properties.parse(config, options);
```

but I am unable to use include that way.  If you add the include option to the example above, the code assumes that a callback exists and tries to call it.  You can eliminate the requirement for a callback by using fs.readFileSync.  This is practical in cases where the file is only read once on application startup, which I imagine would be a very common use case.

**Comment by gagle** [comment]
Ok, got it, but I cannot do this. The whole module is structured with asynchronicity in mind and adding this feature imply a complete refactor. But thanks for the report, I've added a check to ensure that the callback is passed.

The [parse()](https://github.com/gagle/node-properties#parse) function says that if the `include` option is enabled, the callback is mandatory.

Just a tip. Don't assume that the application startup and shutdown are synchronous. For example, database initialization is always asynchronous. This forces the startup step to be async. Design your application to be 100% asynchronous and you won't get this kind of issues.

**Comment by bgmort** [comment]
Sorry for the late response, I've been busy.  Startup steps such as database synchronization are exactly why it would be nice for config loading to be able to be synchronous.  DB initialization requires properties such as db host and password, which are generally going to be pulled from somewhere.  In my app, the very first thing I do is load the properties file, because all the other startup steps depend on it.  It would be easy enough to put all other initialization in a callback after the properties load, but it's much cleaner to do this synchronously.  Consider the reason that require() is synchronous:  It helps keep module code clean, and it is generally done on application startup as opposed to later on.

I know it's a lot of work.  If you don't have time for it that's fine.  I'll try to get to it sometime, because I think it would be useful considering the use cases of a properties file.

**Comment by chouclee** [comment]
In case someone else has same requirement, the workaround to get property synchronously is to read the property file synchronously as string, then parse it.

```
var propertyParser = require("properties");

var file = fs.readFileSync('path').toString(); 
var options = {
  comments: '#',
  ... 
};
try {
  var content = propertyParser.parse(file, options);
  console.log(content);
} catch (error) {
  console.log(error);
}
```

**Comment by MartinMuzatko** [comment]
Does not work with `path` enabled.

So if you need to fetch some data before defining gulp tasks, you are fucked @gagle .
Because gulp does not support defining tasks within a callback.

Edit: path is not needed when using a string. My bad!
